apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prow-crawler-tracker-pvc
  labels:
    app: prow-crawler
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard  # Adjust based on your cluster's available storage classes