apiVersion: v1
kind: Service
metadata:
  name: data-ingestion
  labels:
    app: data-ingestion
spec:
  selector:
    app: data-ingestion
  ports:
    - port: 80
      targetPort: 5002
      protocol: TCP
  type: ClusterIP 